### ISSUE TITLE
Not working on Windows?

### ISSUE THREAD

**Issue by ghost** [codeinthehole/csvfilter#6]
I tried installing it using "pip install  csvfilter".
Installation worked, but for windows the csvfilter file needs a .py ending.
Also, after renaming it I get the following error messages when calling it:

```
C:\temp\csv\incoming>csvfilter
Traceback (most recent call last):
  File "C:\Tools\GSC\Scripts\csvfilter.py", line 6, in <module>
    from csvfilter import Processor, VERSION
  File "C:\Tools\GSC\Scripts\csvfilter.py", line 6, in <module>
    from csvfilter import Processor, VERSION
ImportError: cannot import name Processor
```

**Comment by codeinthehole** [comment]
No Windows support sorry. Apologies for the late reply too.
